//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMIS_Customer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductStocks = new HashSet<ProductStock>();
            this.Categories = new HashSet<Category>();
        }
    
        public int ProductID { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string ImageUrl { get; set; }
        public decimal Price { get; set; }
    
        public virtual ICollection<ProductStock> ProductStocks { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
    }
}
